### ISSUE TITLE
"Tests should pass" after long list command ls -1

### ISSUE THREAD

**Issue by whiteowl911** [freeCodeCamp/rdb-alpha#10]
**Describe the bug**
This bug happens within "Learn Bash by building a boilerplate" Code Road tutorial

**To Reproduce**
1. I ran the tutorial as directed until I was prompted to long list the programs in a folder
2.  ~/project/freeCodeCamp/node_modules is my filepath

**Expected behavior**
I expected to move on within the tutorial

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 10

**Smartphone (please complete the following information):**
 N/A 
![Screenshot 2022-03-03 15 18 57](https://user-images.githubusercontent.com/83243899/156662749-0653c0e6-ba15-4e85-bea6-f53f149c00f7.png)

**Additional context**

**Comment by gikf** [comment]
Hey @whiteowl911

Sorry for late response and thank you for opening this issue.

Command is actually `ls -l` (lowercase L), not `-1`. As such I'm closing this issue.

Thank you and happy coding.
