### ISSUE TITLE
Issue When Re-Running Container 

### ISSUE THREAD

**Issue by ievgenk** [freeCodeCamp/rdb-alpha#11]
When I am trying to rebuild rdb container I am running in an issue of Node being able to install correctly. Appears to be related to this ---> https://github.com/nodesource/distributions/issues/1379

Dockerfile might need to be tweaked to address that.

**Comment by newlime-jacoder** [comment]
same issue here

**Comment by sethhill28** [comment]
same issue here

**Comment by gikf** [comment]
I can confirm this still can be an issue, when starting fresh. There's couple ways to deal with it, from pinning ubuntu version to `20.x`, to trying to use different node version, or installing it in a different way.

@moT01 what do you think? Or wait until nodesource's distribution is up?

**Comment by moT01** [comment]
Pinning ubuntu to 20.04 is probably the best option for now. I think that's the version we were using when we built all these, so it should work without issue.

**Comment by moT01** [comment]
Thanks for pointing out everyone 👍 It should be fixed @ievgenk, @newlime-jacoder, @sethhill28 - you will need to update your repo locally, and possibly clear your docker cache. FYI - the [web version of these](https://www.freecodecamp.org/learn/relational-database/) is available in beta mode, where can earn your certification.
